redis:
  container_name: redis
  image: redis

vote:
  container_name: voting-app
  image: voting-app
  ports:
    - 5000:80
  links:
    - redis

db:
  container_name: db
  image: postgres:9.4
  environment:
    - POSTGRES_HOST_AUTH_METHOD=trust

worker:
  container_name: worker-app
  image: worker-app
  links:
    - redis
    - db

result:
  container_name: result-app
  image: result-app
  ports:
   - 5001:80
  links:
   - db
